### ISSUE TITLE
停止一切侵权行为，包括但不限于删除已上传的源代码及相关密钥

### ISSUE THREAD

**Issue by sfacg** [xingluo233/qiandao#3]
开发者您好，我是菠萝包轻小说网站，经了解您提供的破解源代码和密钥，已被引入国内并广泛传播，致使我司著作权内容被大量盗取，严重侵害了我司合法权益，我们的作者对于自己辛苦创作的内容被人非法盗用也感到很痛心。

请您尽快删除相关项目信息，且不要再上传类似非法内容。

本次情况或其他补充说明，您可以通过邮件方式和我们取得联系：sfacg@sfacg.com，如果问题得不到妥善解决，我们将不得不通过法律手段追究责任。

**Comment by xingluo233** [comment]
已删除相关代码
